sudo: false
addons:
  rethinkdb: '2.3.4'
language: java
jdk:
  - oraclejdk8
  - openjdk8

branches:
  only:
  - master
  - develop
  - release-*

before_install:
 - mvn clean

after_success:
  - mvn clean install -dskipTests
